#ifndef _EXCEPTIONS_ASM_H
#define _EXCEPTIONS_ASM_H

#define SIZE_INTERRUPT_FRAME                60
#define OFFSETOF_INTERRUPT_STATE_EAX        0
#define OFFSETOF_INTERRUPT_STATE_EBX        4
#define OFFSETOF_INTERRUPT_STATE_ECX        8
#define OFFSETOF_INTERRUPT_STATE_EDX        12
#define OFFSETOF_INTERRUPT_STATE_ESP        16
#define OFFSETOF_INTERRUPT_STATE_EBP        20
#define OFFSETOF_INTERRUPT_STATE_ESI        24
#define OFFSETOF_INTERRUPT_STATE_EDI        28
#define OFFSETOF_INTERRUPT_STATE_CS         32
#define OFFSETOF_INTERRUPT_STATE_DS         36
#define OFFSETOF_INTERRUPT_STATE_ES         40
#define OFFSETOF_INTERRUPT_STATE_FS         44
#define OFFSETOF_INTERRUPT_STATE_GS         48
#define OFFSETOF_INTERRUPT_STATE_SS         52
#define OFFSETOF_INTERRUPT_STATE_ERROR_CODE 56

#endif /* _EXCEPTIONS_ASM_H */