/*
Я пофиксил makefile, добавил туда поочередную компиляцию сначала boot.S -> boot.s
 а потом boot.s -> boot.o (в исходном было boot.S -> boot.o). 
Не комплиируется, потому что есть проблемы с этим файлом.
Типо если удалить все (или все кроме первых 13 строк) то все заводится.
Мне кажется тут проблемы какая то с подключениями но хз. Но типо 
сам заголовчник подлючается. 
*/

#ifndef MULTIBOOT_HEADER
#define MULTIBOOT_HEADER 1

/*  How many bytes from the start of the file we search for the header. */
.equ MULTIBOOT_SEARCH, 32768
.equ MULTIBOOT_HEADER_ALIGN, 8

/*  The magic field should contain this. */
.equ MULTIBOOT2_HEADER_MAGIC, 0xe85250d6

/*  This should be in %eax. */
.equ MULTIBOOT2_BOOTLOADER_MAGIC, 0x36d76289

/*  Alignment of multiboot modules. */
.equ MULTIBOOT_MOD_ALIGN, 0x00001000

/*  Alignment of the multiboot info structure. */
.equ MULTIBOOT_INFO_ALIGN, 0x00000008

/*  Flags set in the 'flags' member of the multiboot header. */
.equ MULTIBOOT_TAG_ALIGN, 8
.equ MULTIBOOT_TAG_TYPE_END, 0
.equ MULTIBOOT_TAG_TYPE_CMDLINE, 1
.equ MULTIBOOT_TAG_TYPE_BOOT_LOADER_NAME, 2
.equ MULTIBOOT_TAG_TYPE_MODULE, 3
.equ MULTIBOOT_TAG_TYPE_BASIC_MEMINFO, 4
.equ MULTIBOOT_TAG_TYPE_BOOTDEV, 5
.equ MULTIBOOT_TAG_TYPE_MMAP, 6
.equ MULTIBOOT_TAG_TYPE_VBE, 7
.equ MULTIBOOT_TAG_TYPE_FRAMEBUFFER, 8
.equ MULTIBOOT_TAG_TYPE_ELF_SECTIONS, 9
.equ MULTIBOOT_TAG_TYPE_APM, 10
.equ MULTIBOOT_TAG_TYPE_EFI32, 11
.equ MULTIBOOT_TAG_TYPE_EFI64, 12
.equ MULTIBOOT_TAG_TYPE_SMBIOS, 13
.equ MULTIBOOT_TAG_TYPE_ACPI_OLD, 14
.equ MULTIBOOT_TAG_TYPE_ACPI_NEW, 15
.equ MULTIBOOT_TAG_TYPE_NETWORK, 16
.equ MULTIBOOT_TAG_TYPE_EFI_MMAP, 17
.equ MULTIBOOT_TAG_TYPE_EFI_BS, 18
.equ MULTIBOOT_TAG_TYPE_EFI32_IH, 19
.equ MULTIBOOT_TAG_TYPE_EFI64_IH, 20
.equ MULTIBOOT_TAG_TYPE_LOAD_BASE_ADDR, 21

.equ MULTIBOOT_HEADER_TAG_END, 0
.equ MULTIBOOT_HEADER_TAG_INFORMATION_REQUEST, 1
.equ MULTIBOOT_HEADER_TAG_ADDRESS, 2
.equ MULTIBOOT_HEADER_TAG_ENTRY_ADDRESS, 3
.equ MULTIBOOT_HEADER_TAG_CONSOLE_FLAGS, 4
.equ MULTIBOOT_HEADER_TAG_FRAMEBUFFER, 5
.equ MULTIBOOT_HEADER_TAG_MODULE_ALIGN, 6
.equ MULTIBOOT_HEADER_TAG_EFI_BS, 7
.equ MULTIBOOT_HEADER_TAG_ENTRY_ADDRESS_EFI32, 8
.equ MULTIBOOT_HEADER_TAG_ENTRY_ADDRESS_EFI64, 9
.equ MULTIBOOT_HEADER_TAG_RELOCATABLE, 10

.equ MULTIBOOT_ARCHITECTURE_I386, 0
.equ MULTIBOOT_ARCHITECTURE_MIPS32, 4
.equ MULTIBOOT_HEADER_TAG_OPTIONAL, 1

.equ MULTIBOOT_LOAD_PREFERENCE_NONE, 0
.equ MULTIBOOT_LOAD_PREFERENCE_LOW, 1
.equ MULTIBOOT_LOAD_PREFERENCE_HIGH, 2

.equ MULTIBOOT_CONSOLE_FLAGS_CONSOLE_REQUIRED, 1
.equ MULTIBOOT_CONSOLE_FLAGS_EGA_TEXT_SUPPORTED, 2

#endif